<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search transport
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["transport/new", "Create transport"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "transport/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldMatricule" class="col-sm-2 control-label">Matricule</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["matricule", "size" => 30, "class" => "form-control", "id" => "fieldMatricule"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldModel" class="col-sm-2 control-label">Model</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["model", "size" => 30, "class" => "form-control", "id" => "fieldModel"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldType" class="col-sm-2 control-label">Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["type", "size" => 30, "class" => "form-control", "id" => "fieldType"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEntrepriseSiren" class="col-sm-2 control-label">Entreprise Of Siren</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["entreprise_siren", "type" => "number", "class" => "form-control", "id" => "fieldEntrepriseSiren"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
