<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search etablissement
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["etablissement/new", "Create etablissement"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "etablissement/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldSiret" class="col-sm-2 control-label">Siret</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["siret", "type" => "number", "class" => "form-control", "id" => "fieldSiret"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLantitude" class="col-sm-2 control-label">Lantitude</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["lantitude", "size" => 30, "class" => "form-control", "id" => "fieldLantitude"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLongitude" class="col-sm-2 control-label">Longitude</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["longitude", "size" => 30, "class" => "form-control", "id" => "fieldLongitude"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEntrepriseSiren" class="col-sm-2 control-label">Entreprise Of Siren</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["entreprise_siren", "type" => "number", "class" => "form-control", "id" => "fieldEntrepriseSiren"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
