<!DOCTYPE html>
<head>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
</head>
<body>

  <div class="container">
      <div class="row" id="row1">

              <img src="C:\wamp\www\GeoEntreprise\images\visitez.png" style="width:210px; height:106.035px;"/>

      </div>
  </div>
</body>
